# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.blacklistedKernelModules = [ "nct6683" ];
  boot.kernelModules = [ "kvm-amd" "nct6687" ]; # nct6683 为 MSI 主板内核驱动，通过 sudo sensors-detect 查找
  boot.extraModulePackages = [ config.boot.kernelPackages.nct6687d ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a82da222-59e9-482f-8ee4-99faacad8f78";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7C2F-E93B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
